services:
  - type: web
    name: bookpilot-manager
    env: java
    plan: free
    buildCommand: "echo 'Using prebuilt JAR file â€” no compilation needed'"
    startCommand: "java -jar dist/LMS.jar"
    envVars:
      - key: PORT
        value: 10000
